pipeline{
    agent any
	
	stages{
	  stage('Compile Stage'){
			steps{
				
					sh '''
          cd Student
          mvn clen test package
    '''
		    }
	    }
	    
	    stage('QA Stage'){
			steps{
					sh '''
          cd demoStudent
          mvn clean install sonar:sonar
    '''
				}
		    }
		     stage('Junit test Stage'){
			steps{
				
				junit 'Student/target/surefire-reports/*.xml'
		    }
	    }
	  stage('ansible-deploy'){
	      steps{
		      sh 'ansible-playbook Student/Test.yml'
		  
	        // ansiblePlaybook credentialsId: 'Ansible', disableHostKeyChecking: true, installation: 'AnsibleTest', inventory: 'Student/dev.inv', playbook: 'Student/Test.yml'
	      }
	  }
	    
	}
}
